<?php
include_once(__DIR__ . '/funcs/danh-muc/danh_muc.inc');
include_once(__DIR__ . '/funcs/user/nguoi_dung.inc');
include_once(__DIR__ . '/funcs/vai-tro/vai_tro.inc');
include_once(__DIR__ . '/funcs/phan-quyen/phan_quyen.inc');
include_once(__DIR__ . '/funcs/tong-quan/tong-quan.inc');
include_once(__DIR__ . '/funcs/don_hang.inc');
include_once(__DIR__ . '/funcs/san_pham.inc');
include("includes/password.inc");


/**
 * Implements hook_menu().
 */
function quan_ly_tac_nghiep_web_menu()
{
  // Danh mục
  $items['save-danh-muc'] = [
    'title' => 'Lưu thông tin danh mục',
    'delivery callback' => 'save_danh_muc',
    'access callback' => 'user_access',
    'access_arguments' => ['save_danh_muc'],
  ];
  $items['load-danh-muc'] = [
    'title' => 'Tải thông tin danh mục',
    'delivery callback' => 'load_danh_muc',
    'access callback' => 'user_access',
    'access_arguments' => ['load_danh_muc'],
  ];
  $items['xoa-danh-muc'] = [
    'title' => 'Xoá thông tin danh mục',
    'delivery callback' => 'xoa_danh_muc',
    'access callback' => 'user_access',
    'access_arguments' => ['xoa_danh_muc'],
  ];
  //User
  $items['save-user'] = [
    'title' => 'Lưu thông tin người dùng',
    'delivery callback' => 'save_user',
    'access callback' => 'user_access',
    'access_arguments' => ['save_user_permission'],
  ];
  $items['load-role'] = [
    'title' => 'Load danh sách vai trò',
    'delivery callback' => 'load_role',
    'access callback' => 'user_access',
    'access_arguments' => ['load_role'],
  ];
  $items['xoa-user'] = [
    'title' => 'Xóa thông tin người dùng',
    'delivery callback' => 'xoa_user',
    'access callback' => 'user_access',
    'access_arguments' => ['xoa_user_permission'],
  ];
  $items['load-user'] = [
    'title' => 'Load thông tin người dùng',
    'delivery callback' => 'load_user',
    'access callback' => 'user_access',
    'access_arguments' => ['load_user_permission'],
  ];
  //Vai trò
  $items['save-vai-tro'] = [
    'title' => 'Lưu vai trò',
    'delivery callback' => 'save_vai_tro',
    'access callback' => 'user_access',
    'access_arguments' => ['save_vai_tro_permission'],
  ];
  $items['load-vai-tro'] = [
    'title' => 'load vai trò',
    'delivery callback' => 'load_vai_tro',
    'access callback' => 'user_access',
    'access_arguments' => ['load_vai_tro_permission'],
  ];
  $items['xoa-vai-tro'] = [
    'title' => 'Xóa vai trò',
    'delivery callback' => 'xoa_vai_tro',
    'access callback' => 'user_access',
    'access_arguments' => ['xoa_vai_tro_permission'],
  ];
  $items['save-phan-quyen'] = [
    'title' => 'Lưu thông tin phân quyền',
    'delivery callback' => 'save_phan_quyen',
    'access callback' => 'user_access',
    'access_arguments' => ['save_phan_quyen_permission'],
  ];
  $items['get-thong-ke-hop-dong-by-year'] = [
    'title' => 'Load thông tin thống kê',
    'delivery callback' => 'get_thong_ke_hop_dong_by_year',
    'access callback' => 'user_access',
    'access_arguments' => ['get_thong_ke_hop_dong_by_year_permission'],
  ];
  $items['phan-quyen'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Danh sách phân quyền',
    'page callback' => 'phan_quyen',
    'page arguments' => array('phan_quyen_permission'),
    'access arguments' => array('phan_quyen_permission'),
  );
  $items['vai-tro'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Danh sách vai trò',
    'page callback' => 'vai_tro',
    'page arguments' => array('vai_tro_permission'),
    'access arguments' => array('vai_tro_permission'),
  );
  $items['ho-so-ca-nhan'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Hồ sơ cá nhân',
    'page callback' => 'ho_so_ca_nhan',
    'page arguments' => array('ho_so_ca_nhan_permission'),
    'access arguments' => array('ho_so_ca_nhan_permission'),
  );
  $items['save-logo'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lưu logo',
    'delivery callback' => 'save_logo',
    'access callback' => 'user_access',
    'access arguments' => array('save_logo_permission'),
  );
  $items['save-don-hang'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lưu đơn',
    'delivery callback' => 'save_don_hang',
    'access callback' => 'user_access',
    'access arguments' => array('save_don_hang_permission'),
  );
  $items['xem-don-hang'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Xem đơn',
    'delivery callback' => 'xem_don_hang',
    'access callback' => 'user_access',
    'access arguments' => array('xem_don_hang_permission'),
  );
  $items['load-don-hang'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Sửa đơn',
    'delivery callback' => 'load_don_hang',
    'access callback' => 'user_access',
    'access arguments' => array('load_don_hang_permission'),
  );
  $items['load-trang-thai'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Cập nhật trạng thái đơn',
    'delivery callback' => 'load_trang_thai',
    'access callback' => 'user_access',
    'access arguments' => array('load_trang_thai_permission'),
  );
  $items['xoa-don-hang'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Sửa đơn',
    'delivery callback' => 'xoa_don_hang',
    'access callback' => 'user_access',
    'access arguments' => array('xoa_don_hang_permission'),
  );
  $items['save-trang-thai'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lưu trạng thái',
    'delivery callback' => 'save_trang_thai',
    'access callback' => 'user_access',
    'access arguments' => array('save_trang_thai_permission'),
  );
  $items['he-thong'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Hệ thống',
    'page callback' => 'he_thong',
    'page arguments' => array('he_thong_permission'),
    'access arguments' => array('he_thong_permission'),
  );
  $items['get-khach-hang'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lấy thông tin khách hàng',
    'page callback' => 'get_khach_hang',
    'page arguments' => array('get_khach_hang_permission'),
    'access arguments' => array('get_khach_hang_permission'),
  );
  $items['load-khach-hang'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lấy thông tin đơn hàng bởi khách hàng',
    'page callback' => 'load_khach_hang',
    'page arguments' => array('load_khach_hang_permission'),
    'access arguments' => array('load_khach_hang_permission'),
  );
  $items['save-trang-thai-thanh-toan'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lưu thông tin thanh toán',
    'page callback' => 'save_trang_thai_thanh_toan',
    'page arguments' => array('save_trang_thai_thanh_toan_permission'),
    'access arguments' => array('save_trang_thai_thanh_toan_permission'),
  );
  $items['load-mau-in'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Load mẫu in',
    'page callback' => 'load_mau_in',
    'page arguments' => array('load_mau_in_toan_permission'),
    'access arguments' => array('load_mau_in_toan_permission'),
  );
  $items['save-mau-in'] = [
    'title' => 'Lưu mẫu in thu chi',
    'delivery callback' => 'save_mau_in',
    'access callback' => 'user_access',
    'access_arguments' => ['save_mau_in_permission'],
  ];
  $items['save-san-pham'] = [
    'title' => 'Thêm sản phẩm',
    'delivery callback' => 'save_san_pham',
    'access callback' => 'user_access',
    'access_arguments' => ['save_san_pham_permission'],
  ];
  $items['load-san-pham'] = [
    'title' => 'Sửa sản phẩm',
    'delivery callback' => 'load_san_pham',
    'access callback' => 'user_access',
    'access_arguments' => ['sua_san_pham_permission'],
  ];
  $items['active-san-pham'] = [
    'title' => 'Bật tắt sản phẩm',
    'delivery callback' => 'active_san_pham',
    'access callback' => 'user_access',
    'access_arguments' => ['active_san_pham_permission'],
  ];
  $items['load-diem'] = [
    'title' => 'Hiển thị điểm',
    'delivery callback' => 'load_diem',
    'access callback' => 'user_access',
    'access_arguments' => ['load_diem_permission'],
  ];
  $items['save-doi-diem'] = [
    'title' => 'Lưu đổi điểm',
    'delivery callback' => 'save_doi_diem',
    'access callback' => 'user_access',
    'access_arguments' => ['save_doi_diem_permission'],
  ];
  $items['lich-su-doi-diem'] = [
    'title' => 'Lịch sử đổi điểm',
    'delivery callback' => 'lich_su_doi_diem',
    'access callback' => 'user_access',
    'access_arguments' => ['lich_su_doi_diem_permission'],
  ];
  $items['get-cuoc-dan'] = [
    'title' => 'danh sách cước đan',
    'delivery callback' => 'get_cuoc_dan',
    'access callback' => 'user_access',
    'access_arguments' => ['get_cuoc_dan_permission'],
  ];
  $items['gioi-thieu'] = [
    'title' => 'Giới thiệu',
    'page callback' => 'gioi_thieu',
    'page arguments' => array('gioi_thieu_permission'),
    'access arguments' => array('gioi_thieu_permission'),
  ];
  $items['ket-qua'] = [
    'title' => 'Danh sách liên hệ',
    'page callback' => 'ket_qua',
    'page arguments' => array('ket_qua_permission'),
    'access arguments' => array('ket_qua_permission'),
  ];
  $items['lien-he'] = [
    'title' => 'Liên hệ',
    'page callback' => 'lien_he',
    'page arguments' => array('lien_he_permission'),
    'access arguments' => array('lien_he_permission'),
  ];
  $items['chi-tiet-san-pham'] = [
    'title' => 'Chi tiết sản phẩm',
    'page callback' => 'chi_tiet_san_pham',
    'page arguments' => array('chi_tiet_san_pham_permission'),
    'access arguments' => array('chi_tiet_san_pham_permission'),
  ];
  return $items;
}

/**
 * Implements hook_permission().
 */
function quan_ly_tac_nghiep_web_permission()
{
  return [
    'save_danh_muc' => [
      'title' => 'Lưu thông tin danh mục',
    ],
    'load_danh_muc' => [
      'title' => 'Sửa thông tin danh mục',
    ],
    'xoa_danh_muc' => [
      'title' => 'Xoá thông tin danh mục',
    ],
    'save_user_permission' => [
      'title' => 'Lưu thông tin người dùng',
    ],
    'load_role_permission' => [
      'title' => 'Load thông tin vai trò người dùng',
    ],
    'xoa_user_permission' => [
      'title' => 'Xóa thông tin người dùng',
    ],
    'load_user_permission' => [
      'title' => 'Load thông tin người dùng',
    ],
    'nguoi_dung_permission' => [
      'title' => 'Danh sách người dùng',
    ],
    'save_vai_tro_permission' => [
      'title' => 'Lưu thông tin vai trò',
    ],
    'load_vai_tro_permission' => [
      'title' => 'Cập nhật thông tin vai trò',
    ],
    'xoa_vai_tro_permission' => [
      'title' => 'Xóa thông tin vai trò',
    ],
    'save_phan_quyen_permission' => [
      'title' => 'lưu thông tin phân quyền',
    ],
    'vai_tro_permission' => [
      'title' => 'Danh sách vai trò',
    ],
    'phan_quyen_permission' => [
      'title' => 'Danh sách phân quyền',
    ],
    'get_thong_ke_hop_dong_by_year_permission' => [
      'title' => 'Load thông tin thống kê',
    ],
    'ho_so_ca_nhan_permission' => [
      'title' => 'Hồ sơ cá nhân',
    ],
    'save_logo_permission' => [
      'title' => 'Cập nhật logo',
    ],
    'get_list_user_permission' => [
      'title' => 'Thêm thu chi',
    ],
    'danh_muc_permission' => [
      'title' => 'Danh sách danh mục',
    ],
    'save_don_hang_permission' => [
      'title' => 'Tạo đơn hàng',
    ],
    'xem_don_hang_permission' => [
      'title' => 'Xem đơn hàng',
    ],
    'load_don_hang_permission' => [
      'title' => 'Sửa đơn hàng',
    ],
    'xoa_don_hang_permission' => [
      'title' => 'Xóa đơn hàng',
    ],
    'load_trang_thai_permission' => [
      'title' => 'Xem trạng thái  đơn hàng',
    ],
    'save_trang_thai_permission' => [
      'title' => 'Lưu trạng thái',
    ],
    'he_thong_permission' => [
      'title' => 'Hệ thống',
    ],
    'get_khach_hang_permission' => [
      'title' => 'Lấy thông tin khách hàng',
    ],
    'load_khach_hang_permission' => [
      'title' => 'Lấy thông tin đơn hàng bởi khách hàng',
    ],
    'load_mau_in_toan_permission' => [
      'title' => 'In phiếu',
    ],
    'save_mau_in_permission' => [
      'title' => 'Lưu mẫu in',
    ],
    'save_trang_thai_thanh_toan_permission' => [
      'title' => 'Lưu trạng thái thanh toán',
    ],
    'save_san_pham_permission' => [
      'title' => 'Lưu sản phẩm',
    ],
    'load_san_pham_permission' => [
      'title' => 'Sửa sản phẩm',
    ],
    'active_san_pham_permission' => [
      'title' => 'Bật tắt sản phẩm',
    ],
    'load_diem_permission' => [
      'title' => 'Hiển thị điểm',
    ],
    'save_doi_diem_permission' => [
      'title' => 'Lưu đổi điểm',
    ],
    'lich_su_doi_diem_permission' => [
      'title' => 'Lịch sử đổi điểm',
    ],
    'get_cuoc_dan_permission' => [
      'title' => 'Danh sách cước đan',
    ],
    'gioi_thieu_permission' => [
      'title' => 'Giới thiệu',
    ],
    'lien_he_permission' => [
      'title' => 'Liên hệ',
    ],
    'chi_tiet_san_pham_permission' => [
      'title' => 'Chi tiết sản phẩm',
    ],
    'ket_qua_permission' => [
      'title' => 'Danh sách kết quả',
    ],
  ];
}

/**
 * @throws Exception
 */
function quan_ly_tac_nghiep_web_user_login(&$edit, $account)
{
  $edit['redirect'] = '/';
}
function quan_ly_tac_nghiep_web_views_query_alter(&$view, &$query)
{
  if($view->name == 'danh_sach_noi_dung') {
    if(
      $view->current_display=='page_tra_cuu_don'
    ){
      global $user;
      if($user->uid != 1){
        if(isset($user->roles[8]))
          $query->where[1]['conditions'][] = [
            'field' => 'field_data_field_khach_hang_id.field_khach_hang_id_target_id',
            'value' => intval($user->uid),
            'operator' => '='
          ];
      }
    }

  }
}
function gioi_thieu() {
  return [
    '#type' => 'markup',
  ];
}
function lien_he() {
  return [
    '#type' => 'markup',
  ];
}
function chi_tiet_san_pham() {
  return [
    '#type' => 'markup',
  ];
}
function ket_qua() {
  return [
    '#type' => 'markup',
  ];
}
