<?php
include_once(__DIR__ . '/funcs/danh-muc/danh_muc.inc');
include_once(__DIR__ . '/funcs/user/nguoi_dung.inc');
include_once(__DIR__ . '/funcs/vai-tro/vai_tro.inc');
include_once(__DIR__ . '/funcs/phan-quyen/phan_quyen.inc');
include_once(__DIR__ . '/funcs/tong-quan/tong-quan.inc');
include_once(__DIR__ . '/funcs/glocal.inc');
include_once(__DIR__ . '/funcs/cau_hoi.inc');
include("includes/password.inc");


/**
 * Implements hook_menu().
 */
function quan_ly_tac_nghiep_web_menu()
{
  // Danh mục
  $items['save-danh-muc'] = [
    'title' => 'Lưu thông tin danh mục',
    'delivery callback' => 'save_danh_muc',
    'access callback' => 'user_access',
    'access_arguments' => ['save_danh_muc'],
  ];
  $items['load-danh-muc'] = [
    'title' => 'Tải thông tin danh mục',
    'delivery callback' => 'load_danh_muc',
    'access callback' => 'user_access',
    'access_arguments' => ['load_danh_muc'],
  ];
  $items['xoa-danh-muc'] = [
    'title' => 'Xoá thông tin danh mục',
    'delivery callback' => 'xoa_danh_muc',
    'access callback' => 'user_access',
    'access_arguments' => ['xoa_danh_muc'],
  ];
  //User
  $items['save-user'] = [
    'title' => 'Lưu thông tin người dùng',
    'delivery callback' => 'save_user',
    'access callback' => 'user_access',
    'access_arguments' => ['save_user_permission'],
  ];
  $items['load-role'] = [
    'title' => 'Load danh sách vai trò',
    'delivery callback' => 'load_role',
    'access callback' => 'user_access',
    'access_arguments' => ['load_role'],
  ];
  $items['xoa-user'] = [
    'title' => 'Xóa thông tin người dùng',
    'delivery callback' => 'xoa_user',
    'access callback' => 'user_access',
    'access_arguments' => ['xoa_user_permission'],
  ];
  $items['load-user'] = [
    'title' => 'Load thông tin người dùng',
    'delivery callback' => 'load_user',
    'access callback' => 'user_access',
    'access_arguments' => ['load_user_permission'],
  ];
  //Vai trò
  $items['save-vai-tro'] = [
    'title' => 'Lưu vai trò',
    'delivery callback' => 'save_vai_tro',
    'access callback' => 'user_access',
    'access_arguments' => ['save_vai_tro_permission'],
  ];
  $items['load-vai-tro'] = [
    'title' => 'load vai trò',
    'delivery callback' => 'load_vai_tro',
    'access callback' => 'user_access',
    'access_arguments' => ['load_vai_tro_permission'],
  ];
  $items['xoa-vai-tro'] = [
    'title' => 'Xóa vai trò',
    'delivery callback' => 'xoa_vai_tro',
    'access callback' => 'user_access',
    'access_arguments' => ['xoa_vai_tro_permission'],
  ];
  $items['save-phan-quyen'] = [
    'title' => 'Lưu thông tin phân quyền',
    'delivery callback' => 'save_phan_quyen',
    'access callback' => 'user_access',
    'access_arguments' => ['save_phan_quyen_permission'],
  ];
  $items['get-thong-ke-hop-dong-by-year'] = [
    'title' => 'Load thông tin thống kê',
    'delivery callback' => 'get_thong_ke_hop_dong_by_year',
    'access callback' => 'user_access',
    'access_arguments' => ['get_thong_ke_hop_dong_by_year_permission'],
  ];
  $items['phan-quyen'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Danh sách phân quyền',
    'page callback' => 'phan_quyen',
    'page arguments' => array('phan_quyen_permission'),
    'access arguments' => array('phan_quyen_permission'),
  );
  $items['vai-tro'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Danh sách vai trò',
    'page callback' => 'vai_tro',
    'page arguments' => array('vai_tro_permission'),
    'access arguments' => array('vai_tro_permission'),
  );
  $items['ho-so-ca-nhan'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Hồ sơ cá nhân',
    'page callback' => 'ho_so_ca_nhan',
    'page arguments' => array('ho_so_ca_nhan_permission'),
    'access arguments' => array('ho_so_ca_nhan_permission'),
  );
  $items['save-logo'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lưu logo',
    'delivery callback' => 'save_logo',
    'access callback' => 'user_access',
    'access arguments' => array('save_logo_permission'),
  );
  $items['active'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Active',
    'delivery callback' => 'active',
    'access callback' => 'user_access',
    'access arguments' => array('active_permission'),
  );
  $items['xoa-node'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Xóa node',
    'delivery callback' => 'xoa_node',
    'access callback' => 'user_access',
    'access arguments' => array('xoa_node_permission'),
  );
  $items['he-thong'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Hệ thống',
    'page callback' => 'he_thong',
    'page arguments' => array('he_thong_permission'),
    'access arguments' => array('he_thong_permission'),
  );
  $items['khao-sat'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Khảo sát',
    'page callback' => 'khao_sat',
    'page arguments' => array('khao_sat_permission'),
    'access arguments' => array('khao_sat_permission'),
  );
  $items['save-cau-hoi'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Lưu câu hỏi',
    'delivery callback' => 'save_cau_hoi',
    'access callback' => 'user_access',
    'access arguments' => array('save_cau_hoi_permission'),
  );
  $items['load-cau-hoi'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'load câu hỏi',
    'delivery callback' => 'load_cau_hoi',
    'access callback' => 'user_access',
    'access arguments' => array('load_cau_hoi_permission'),
  );
  $items['xem-khao-sat'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Xem khảo sát',
    'delivery callback' => 'xem_khao_sat',
    'access callback' => 'user_access',
    'access arguments' => array('xem_khao_sat_permission'),
  );
  $items['save-khao-sat'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Save khảo sát',
    'delivery callback' => 'save_khao_sat',
    'access callback' => 'user_access',
    'access arguments' => array('save_khao_sat_permission'),
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function quan_ly_tac_nghiep_web_permission()
{
  return [
    'save_danh_muc' => [
      'title' => 'Lưu thông tin danh mục',
    ],
    'load_danh_muc' => [
      'title' => 'Sửa thông tin danh mục',
    ],
    'xoa_danh_muc' => [
      'title' => 'Xoá thông tin danh mục',
    ],
    'save_user_permission' => [
      'title' => 'Lưu thông tin người dùng',
    ],
    'load_role_permission' => [
      'title' => 'Load thông tin vai trò người dùng',
    ],
    'xoa_user_permission' => [
      'title' => 'Xóa thông tin người dùng',
    ],
    'load_user_permission' => [
      'title' => 'Load thông tin người dùng',
    ],
    'nguoi_dung_permission' => [
      'title' => 'Danh sách người dùng',
    ],
    'save_vai_tro_permission' => [
      'title' => 'Lưu thông tin vai trò',
    ],
    'load_vai_tro_permission' => [
      'title' => 'Cập nhật thông tin vai trò',
    ],
    'xoa_vai_tro_permission' => [
      'title' => 'Xóa thông tin vai trò',
    ],
    'save_phan_quyen_permission' => [
      'title' => 'lưu thông tin phân quyền',
    ],
    'vai_tro_permission' => [
      'title' => 'Danh sách vai trò',
    ],
    'phan_quyen_permission' => [
      'title' => 'Danh sách phân quyền',
    ],
    'get_thong_ke_hop_dong_by_year_permission' => [
      'title' => 'Load thông tin thống kê',
    ],
    'ho_so_ca_nhan_permission' => [
      'title' => 'Hồ sơ cá nhân',
    ],
    'save_logo_permission' => [
      'title' => 'Cập nhật logo',
    ],
    'get_list_user_permission' => [
      'title' => 'Thêm thu chi',
    ],
    'danh_muc_permission' => [
      'title' => 'Danh sách danh mục',
    ],
    'he_thong_permission' => [
      'title' => 'Hệ thống',
    ],
    'khao_sat_permission' => [
      'title' => 'Khảo sát',
    ],
    'active_permission' => [
      'title' => 'Active',
    ],
    'save_cau_hoi_permission' => [
      'title' => 'Lưu câu hỏi',
    ],
    'xoa_node_permission' => [
      'title' => 'Xóa node',
    ],
    'load_cau_hoi_permission' => [
      'title' => 'Load câu hỏi',
    ],
    'xem_khao_sat_permission' => [
      'title' => 'Xem khảo sát',
    ],
    'save_khao_sat_permission' => [
      'title' => 'Save khảo sát',
    ],
  ];
}

/**
 * @throws Exception
 */
function quan_ly_tac_nghiep_web_user_login(&$edit, $account)
{
  $edit['redirect'] = '/';
}
function quan_ly_tac_nghiep_web_views_query_alter(&$view, &$query)
{
  if($view->name == 'danh_sach_noi_dung') {
    if(
      $view->current_display=='page_tra_cuu_don'
    ){
      global $user;
      if($user->uid != 1){
        if(isset($user->roles[8]))
          $query->where[1]['conditions'][] = [
            'field' => 'field_data_field_khach_hang_id.field_khach_hang_id_target_id',
            'value' => intval($user->uid),
            'operator' => '='
          ];
      }
    }

  }
}
function gioi_thieu() {
  return [
    '#type' => 'markup',
  ];
}
function lien_he() {
  return [
    '#type' => 'markup',
  ];
}
function chi_tiet_san_pham() {
  return [
    '#type' => 'markup',
  ];
}
function khao_sat() {
  return [
    '#type' => 'markup',
  ];
}
function ket_qua() {
  return [
    '#type' => 'markup',
  ];
}
function getCountry(){
  $curl = curl_init();

  curl_setopt_array($curl, array(
    CURLOPT_URL => 'https://countriesnow.space/api/v0.1/countries/population',
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'GET',
  ));

  $response = curl_exec($curl);
  $data = isset((json_decode($response))->data)?(json_decode($response))->data:[];
  curl_close($curl);
  return $data;
}
function quan_ly_tac_nghiep_web_user_presave(&$edit, $account, $category)
{
  if (isset($account->is_new) && !empty($account->is_new)) {
    if (isset($edit['roles'])) {
      $edit['roles'] = [
        2 => 'authenticated user',
        8 => 'my custom role',
      ];
    }
  }
}
function getListImage(){
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', "banner")
    ->propertyOrderBy('nid', 'DESC');
  $query->fieldCondition('field_hoat_dong','value',1);
  $results = $query->execute();
  $nids = array_keys($results['node']);
  return [
    'data' => node_load_multiple($nids),
  ];
}
function getListKhaoSat(){
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', "cau_hoi")
    ->propertyOrderBy('nid', 'DESC');
  $query->fieldCondition('field_hoat_dong','value',1);
  $results = $query->execute();
  $nids = array_keys($results['node']);
  return [
    'data' => node_load_multiple($nids),
  ];
}
function checKhaoSat($khao_sat_id){
  global $user;
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', "khao_sat");
  $query->fieldCondition('field_hoat_dong','value',1);
  $query->fieldCondition('field_khao_sat_id','target_id',$khao_sat_id);
  $query->fieldCondition('field_khach_hang_id','target_id',$user->uid);
  $results = $query->execute();
  $nids = array_keys($results['node']);
  if (count($nids)==0){
    return  false;
  }
  $data =  node_load_multiple($nids);
  foreach ($data as $item){
    return  $item;
  }
  return  false;
}
